import { Inter } from "next/font/google";
import "./globals.css";
import {Montserrat} from 'next/font/google'
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-mont'
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={`${montserrat.variable} font-mont  bg-light min-h-screen dark:bg-dark   w-full `}>
        <Navbar></Navbar>
        <div>
        {children}
        </div>
        <Footer></Footer>
        </body>
    </html>
  );
}
